fos_ck_editor:
    configs:
        my_config:
            toolbar:                "full"
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            uiColor:                "#e2e2e2"
            